In [3]:
import pandas as pd
import numpy as np

import autorootcwd  # noqa
from hamilton import driver

from functools import partial
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import (
    RandomizedSearchCV,
)
from scipy.stats import randint, loguniform
from sklearn.metrics import roc_auc_score

In [4]:
from src.data.data_splits import (split_cwru_proposed, cwru_optimization_split)
from itertools import combinations, product
import random

In [ ]:
def get_cv_splits(
    metadata_df: pd.DataFrame,
    run: int,
    train_side: str = "DE",
    pct = 1,
    test_size = "2x1",
):
    
    no_duplicate = metadata_df.drop_duplicates(subset=["waveform_id"]).copy()

    train, _ , test = split_cwru_proposed(
        metadata_df=no_duplicate,
        run=run,
        normal_train_side= train_side,
        split_ratio = test_size,
    )
    
    train_idx = train.index.tolist()
    test_idx = test.index.tolist()

    train_df = metadata_df[metadata_df["waveform_id"].isin(train["waveform_id"])]
    train_idx = train_df.index.tolist()
    
    test_df = metadata_df[metadata_df["waveform_id"].isin(test["waveform_id"])]
    test_idx = test_df.index.tolist()

    cv = (train_idx, test_idx)

    return cv

def get_opt_splits(
    fold: int,
    metadata_df: pd.DataFrame,
    train_side: str = "DE",
):
    test = pd.read_parquet(f"data/splits/cwru/tuning/fold_{fold}/test_{train_side}.parquet")
    train = pd.read_parquet(f"data/splits/cwru/tuning/fold_{fold}/train_{train_side}.parquet")

    train_df = metadata_df[metadata_df["waveform_id"].isin(train["waveform_id"])]
    train_idx = train_df.index.tolist()
    
    test_df = metadata_df[metadata_df["waveform_id"].isin(test["waveform_id"])]
    test_idx = test_df.index.tolist()

    cv = (train_idx, test_idx)

    return cv

In [6]:
metadata = pd.read_pickle("data/metadata/cwru/files_metadata.bz2")
features = pd.read_parquet("data/features/cwru_features_segmented.parquet") # Features with 10 segments of 1s per signal

In [7]:
metadata.head()

,waveform_id,fault_location,load,rpm,fault_type,fault_size,signal_location,fs,duration,bpfo,bpfi,bsf,ftf,inner,outer,ball,multiclass_label
0,IR_7_DE_DE_48_1HP,DE,1,1772,IR,7,DE,48000,10.129667,3.5848,5.4152,2.35675,0.39828,1,0,0,1
1,IR_7_DE_FE_48_1HP,DE,1,1772,IR,7,FE,48000,10.129667,3.0530,4.9469,1.99370,0.38170,0,0,0,0
2,B_7_DE_DE_12_1HP,DE,1,1772,B,7,DE,12000,10.117500,3.5848,5.4152,2.35675,0.39828,0,0,1,3
3,B_7_DE_FE_12_1HP,DE,1,1772,B,7,FE,12000,10.117500,3.0530,4.9469,1.99370,0.38170,0,0,0,0
4,B_7_DE_BA_12_1HP,DE,1,1772,B,7,BA,12000,10.117500,3.5848,5.4152,4.71350,0.39828,0,0,0,0

In [8]:
df = features.merge(metadata, on="waveform_id", how="left")

In [9]:
df.shape

(1440, 43)

In [13]:
val_cvs = [get_opt_splits(
    fold=run,
    metadata_df=df,
    train_side=side)
 for (run, side) in product(
    range(1,4), ["FE", "DE"])]

cvs = [get_cv_splits(
    metadata_df=df,
    run=run,
    train_side=side, test_size = "2x1")
 for (run, side) in product(
    range(3,53), ["FE", "DE"])]

Test set on run 22 matches one of the tuning folds. Recreating split with another seed.
New test set on run 222 does not match any of the tuning folds. Split created successfully.
Test set on run 22 matches one of the tuning folds. Recreating split with another seed.
New test set on run 222 does not match any of the tuning folds. Split created successfully.

In [14]:
len(val_cvs), len(cvs)

(6, 100)

In [15]:
len(cvs[0][0])

720

In [16]:
len(val_cvs[0][0])

720

In [17]:
df.iloc[cvs[0][1]].waveform_id_seg.nunique(), df.iloc[cvs[0][0]].waveform_id_seg.value_counts()

(360,
 waveform_id_seg
 B_21_DE_FE_12_2HP_6616     1
 B_21_DE_FE_12_2HP_6615     1
 B_21_DE_FE_12_2HP_6614     1
 B_21_DE_FE_12_2HP_6613     1
 B_21_DE_DE_12_2HP_6612     1
                           ..
 OR@6_7_DE_DE_12_2HP_115    1
 OR@6_7_DE_DE_12_2HP_114    1
 OR@6_7_DE_DE_12_2HP_113    1
 OR@6_7_DE_DE_12_2HP_112    1
 OR@6_7_DE_DE_12_2HP_111    1
 Name: count, Length: 720, dtype: int64)

In [18]:
features = [ 'acceleration/rms/global', 'acceleration/pk-pk/global',
       'acceleration/kurt/global', 'acceleration/skewness/global',
       'acceleration/fc/global',
       'envelope/spectralPeak/1.0x-bpfo/500-6000',
       'envelope/spectralPeak/2.0x-bpfo/500-6000',
       'envelope/spectralPeak/3.0x-bpfo/500-6000',
       'envelope/spectralPeak/4.0x-bpfo/500-6000',
       'envelope/spectralPeak/5.0x-bpfo/500-6000',
       'envelope/spectralPeak/1.0x-bpfi/500-6000',
       'envelope/spectralPeak/2.0x-bpfi/500-6000',
       'envelope/spectralPeak/3.0x-bpfi/500-6000',
       'envelope/spectralPeak/4.0x-bpfi/500-6000',
       'envelope/spectralPeak/5.0x-bpfi/500-6000',
       'envelope/spectralPeak/1.0x-bsf/500-6000',
       'envelope/spectralPeak/2.0x-bsf/500-6000',
       'envelope/spectralPeak/3.0x-bsf/500-6000',
       'envelope/spectralPeak/4.0x-bsf/500-6000',
       'envelope/spectralPeak/5.0x-bsf/500-6000']

In [19]:
X = df[features].copy()
y = df[['inner', 'outer', 'ball']].copy()

# Features (segmented)

## RF

In [20]:
random_search = RandomizedSearchCV(
    estimator=MultiOutputClassifier(RandomForestClassifier()),
    param_distributions={
        "estimator__n_estimators": [200],
        "estimator__max_features": ["sqrt", "log2"],
        "estimator__criterion": ["gini", "entropy", "log_loss"],
        "estimator__max_depth": randint(low=2, high=60),
        "estimator__min_samples_split": randint(low=2, high=20),
        "estimator__min_samples_leaf": randint(low=1, high=20),
        "estimator__ccp_alpha": loguniform(1e-5, 1),
    },
    n_iter=250,
    cv=val_cvs,
    scoring="roc_auc",
    verbose=2,
    n_jobs=-1,
    random_state=42
)

random_search.fit(X, y)

Fitting 6 folds for each of 250 candidates, totalling 1500 fits
[CV] END estimator__ccp_alpha=0.0007459343285726547, estimator__criterion=gini, estimator__max_depth=16, estimator__max_features=sqrt, estimator__min_samples_leaf=8, estimator__min_samples_split=8, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.0007459343285726547, estimator__criterion=gini, estimator__max_depth=16, estimator__max_features=sqrt, estimator__min_samples_leaf=8, estimator__min_samples_split=8, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=1.0090061869151556e-05, estimator__criterion=gini, estimator__max_depth=34, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=18, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.0007459343285726547, estimator__criterion=gini, estimator__max_depth=16, estimator__max_features=sqrt, estimator__min_samples_leaf=8, estimator__min_samples_split=8, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=1.0090061869151556e-05, estimator__criterion=gini, estimator__max_depth=34, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=18, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.034702669886504146, estimator__criterion=entropy, estimator__max_depth=54, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=7, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0007459343285726547, estimator__criterion=gini, estimator__max_depth=16, estimator__max_features=sqrt, estimator__min_samples_leaf=8, estimator__min_samples_split=8, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.0007459343285726547, estimator__criterion=gini, estimator__max_depth=16, estimator__max_features=sqrt, estimator__min_samples_leaf=8, estimator__min_samples_split=8, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.0007459343285726547, estimator__criterion=gini, estimator__max_depth=16, estimator__max_features=sqrt, estimator__min_samples_leaf=8, estimator__min_samples_split=8, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=1.0090061869151556e-05, estimator__criterion=gini, estimator__max_depth=34, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=18, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.0016949768237884727, estimator__criterion=log_loss, estimator__max_depth=12, estimator__max_features=sqrt, estimator__min_samples_leaf=4, estimator__min_samples_split=9, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=1.0090061869151556e-05, estimator__criterion=gini, estimator__max_depth=34, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=18, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=1.0090061869151556e-05, estimator__criterion=gini, estimator__max_depth=34, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=18, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=1.0090061869151556e-05, estimator__criterion=gini, estimator__max_depth=34, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=18, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.0016949768237884727, estimator__criterion=log_loss, estimator__max_depth=12, estimator__max_features=sqrt, estimator__min_samples_leaf=4, estimator__min_samples_split=9, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.034702669886504146, estimator__criterion=entropy, estimator__max_depth=54, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=7, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.034702669886504146, estimator__criterion=entropy, estimator__max_depth=54, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=7, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0016949768237884727, estimator__criterion=log_loss, estimator__max_depth=12, estimator__max_features=sqrt, estimator__min_samples_leaf=4, estimator__min_samples_split=9, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.034702669886504146, estimator__criterion=entropy, estimator__max_depth=54, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=7, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0016949768237884727, estimator__criterion=log_loss, estimator__max_depth=12, estimator__max_features=sqrt, estimator__min_samples_leaf=4, estimator__min_samples_split=9, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.034702669886504146, estimator__criterion=entropy, estimator__max_depth=54, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=7, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0016949768237884727, estimator__criterion=log_loss, estimator__max_depth=12, estimator__max_features=sqrt, estimator__min_samples_leaf=4, estimator__min_samples_split=9, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.034702669886504146, estimator__criterion=entropy, estimator__max_depth=54, estimator__max_features=log2, estimator__min_samples_leaf=12, estimator__min_samples_split=7, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0016949768237884727, estimator__criterion=log_loss, estimator__max_depth=12, estimator__max_features=sqrt, estimator__min_samples_leaf=4, estimator__min_samples_split=9, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.004206039057901996, estimator__criterion=log_loss, estimator__max_depth=43, estimator__max_features=log2, estimator__min_samples_leaf=16, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.004206039057901996, estimator__criterion=log_loss, estimator__max_depth=43, estimator__max_features=log2, estimator__min_samples_leaf=16, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.010907475835157693, estimator__criterion=gini, estimator__max_depth=10, estimator__max_features=sqrt, estimator__min_samples_leaf=18, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.010907475835157693, estimator__criterion=gini, estimator__max_depth=10, estimator__max_features=sqrt, estimator__min_samples_leaf=18, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.004206039057901996, estimator__criterion=log_loss, estimator__max_depth=43, estimator__max_features=log2, estimator__min_samples_leaf=16, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.010907475835157693, estimator__criterion=gini, estimator__max_depth=10, estimator__max_features=sqrt, estimator__min_samples_leaf=18, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.010907475835157693, estimator__criterion=gini, estimator__max_depth=10, estimator__max_features=sqrt, estimator__min_samples_leaf=18, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.004206039057901996, estimator__criterion=log_loss, estimator__max_depth=43, estimator__max_features=log2, estimator__min_samples_leaf=16, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.010907475835157693, estimator__criterion=gini, estimator__max_depth=10, estimator__max_features=sqrt, estimator__min_samples_leaf=18, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.010907475835157693, estimator__criterion=gini, estimator__max_depth=10, estimator__max_features=sqrt, estimator__min_samples_leaf=18, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.004206039057901996, estimator__criterion=log_loss, estimator__max_depth=43, estimator__max_features=log2, estimator__min_samples_leaf=16, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0019069966103000427, estimator__criterion=log_loss, estimator__max_depth=52, estimator__max_features=log2, estimator__min_samples_leaf=3, estimator__min_samples_split=6, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.004206039057901996, estimator__criterion=log_loss, estimator__max_depth=43, estimator__max_features=log2, estimator__min_samples_leaf=16, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0019069966103000427, estimator__criterion=log_loss, estimator__max_depth=52, estimator__max_features=log2, estimator__min_samples_leaf=3, estimator__min_samples_split=6, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0019069966103000427, estimator__criterion=log_loss, estimator__max_depth=52, estimator__max_features=log2, estimator__min_samples_leaf=3, estimator__min_samples_split=6, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.5140540420871593, estimator__criterion=entropy, estimator__max_depth=51, estimator__max_features=log2, estimator__min_samples_leaf=9, estimator__min_samples_split=3, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.5140540420871593, estimator__criterion=entropy, estimator__max_depth=51, estimator__max_features=log2, estimator__min_samples_leaf=9, estimator__min_samples_split=3, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0019069966103000427, estimator__criterion=log_loss, estimator__max_depth=52, estimator__max_features=log2, estimator__min_samples_leaf=3, estimator__min_samples_split=6, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.5140540420871593, estimator__criterion=entropy, estimator__max_depth=51, estimator__max_features=log2, estimator__min_samples_leaf=9, estimator__min_samples_split=3, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0019069966103000427, estimator__criterion=log_loss, estimator__max_depth=52, estimator__max_features=log2, estimator__min_samples_leaf=3, estimator__min_samples_split=6, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.0019069966103000427, estimator__criterion=log_loss, estimator__max_depth=52, estimator__max_features=log2, estimator__min_samples_leaf=3, estimator__min_samples_split=6, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.5140540420871593, estimator__criterion=entropy, estimator__max_depth=51, estimator__max_features=log2, estimator__min_samples_leaf=9, estimator__min_samples_split=3, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.5140540420871593, estimator__criterion=entropy, estimator__max_depth=51, estimator__max_features=log2, estimator__min_samples_leaf=9, estimator__min_samples_split=3, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.5140540420871593, estimator__criterion=entropy, estimator__max_depth=51, estimator__max_features=log2, estimator__min_samples_leaf=9, estimator__min_samples_split=3, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.026373339933815243, estimator__criterion=log_loss, estimator__max_depth=8, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=7.359075652019388e-05, estimator__criterion=gini, estimator__max_depth=37, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=7.359075652019388e-05, estimator__criterion=gini, estimator__max_depth=37, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=7.359075652019388e-05, estimator__criterion=gini, estimator__max_depth=37, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.026373339933815243, estimator__criterion=log_loss, estimator__max_depth=8, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.026373339933815243, estimator__criterion=log_loss, estimator__max_depth=8, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=7.359075652019388e-05, estimator__criterion=gini, estimator__max_depth=37, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.0s
[CV] END estimator__ccp_alpha=0.026373339933815243, estimator__criterion=log_loss, estimator__max_depth=8, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=7.359075652019388e-05, estimator__criterion=gini, estimator__max_depth=37, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=7.359075652019388e-05, estimator__criterion=gini, estimator__max_depth=37, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=5, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.026373339933815243, estimator__criterion=log_loss, estimator__max_depth=8, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.026373339933815243, estimator__criterion=log_loss, estimator__max_depth=8, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=16, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.00036187233309596217, estimator__criterion=entropy, estimator__max_depth=55, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=19, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.00036187233309596217, estimator__criterion=entropy, estimator__max_depth=55, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=19, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.00036187233309596217, estimator__criterion=entropy, estimator__max_depth=55, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=19, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.07510418138777546, estimator__criterion=entropy, estimator__max_depth=11, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=15, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.00036187233309596217, estimator__criterion=entropy, estimator__max_depth=55, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=19, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.00036187233309596217, estimator__criterion=entropy, estimator__max_depth=55, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=19, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.07510418138777546, estimator__criterion=entropy, estimator__max_depth=11, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=15, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.00036187233309596217, estimator__criterion=entropy, estimator__max_depth=55, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=19, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.07510418138777546, estimator__criterion=entropy, estimator__max_depth=11, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=15, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.07510418138777546, estimator__criterion=entropy, estimator__max_depth=11, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=15, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.07510418138777546, estimator__criterion=entropy, estimator__max_depth=11, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=15, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.07510418138777546, estimator__criterion=entropy, estimator__max_depth=11, estimator__max_features=log2, estimator__min_samples_leaf=4, estimator__min_samples_split=15, estimator__n_estimators=200; total time=   1.2s
[CV] END estimator__ccp_alpha=0.04328724829857121, estimator__criterion=log_loss, estimator__max_depth=9, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=17, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0003029476085280711, estimator__criterion=gini, estimator__max_depth=2, estimator__max_features=sqrt, estimator__min_samples_leaf=7, estimator__min_samples_split=10, estimator__n_estimators=200; total time=   0.9s
[CV] END estimator__ccp_alpha=0.0003029476085280711, estimator__criterion=gini, estimator__max_depth=2, estimator__max_features=sqrt, estimator__min_samples_leaf=7, estimator__min_samples_split=10, estimator__n_estimators=200; total time=   0.9s
[CV] END estimator__ccp_alpha=0.0003029476085280711, estimator__criterion=gini, estimator__max_depth=2, estimator__max_features=sqrt, estimator__min_samples_leaf=7, estimator__min_samples_split=10, estimator__n_estimators=200; total time=   0.9s
[CV] END estimator__ccp_alpha=0.04328724829857121, estimator__criterion=log_loss, estimator__max_depth=9, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=17, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.04328724829857121, estimator__criterion=log_loss, estimator__max_depth=9, estimator__max_features=log2, estimator__min_samples_leaf=8, estimator__min_samples_split=17, estimator__n_estimators=200; total time=   1.1s
[CV] END estimator__ccp_alpha=0.0003029476085280711, estimator__criterion=gini, estimator__max_depth=2, estimator__max_features=sqrt, estimator__min_samples_leaf=7, estimator__min_samples_split=10, estimator__n_estimators=200; total time=   0.9s
[CV] END estimator__ccp_alpha=0.0003029476085280711, estimator__criterion=gini, estimator__max_depth=2, estimator__max_features=sqrt, estimator__min_samples_leaf=7, estimator__min_samples_split=10, estimator__n_estimators=200; total time=   0.9s

RandomizedSearchCV(cv=[([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
                         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, ...],
                        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
                         94, 95, 96, 97, 98, 99, 140, 141, 142, 143, 144, 145,
                         146, 147, 148, 149, ...]),
                       ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 20, 21, 22, 23, 24, 25,
                         26, 27, 28, 29, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, ...],
                        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 140, 141, 142,
                         143...
                                        'estimator__max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7fce797c1990>,
                                        'estimator__max_features': ['sqrt',
                                                                    'log2'],
                                        'estimator__min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7fce18779cd0>,
                                        'estimator__min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7fce1877a010>,
                                        'estimator__n_estimators': [200]},
                   random_state=42, scoring='roc_auc', verbose=2)

In [21]:
results = pd.DataFrame(random_search.cv_results_).sort_values(by="rank_test_score")

In [22]:
results.head(10)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_estimator__ccp_alpha,param_estimator__criterion,param_estimator__max_depth,param_estimator__max_features,param_estimator__min_samples_leaf,param_estimator__min_samples_split,...,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,split5_test_score,mean_test_score,std_test_score,rank_test_score
45,0.997307,0.018258,0.038345,0.001094,0.000064,entropy,3,log2,3,17,...,{'estimator__ccp_alpha': 6.368545516399493e-05...,0.805923,0.792388,0.837307,0.868586,0.913363,0.910060,0.854604,0.047017,1
47,1.060954,0.020416,0.037547,0.000563,0.054008,log_loss,4,sqrt,1,17,...,"{'estimator__ccp_alpha': 0.05400786701286533, ...",0.802552,0.760551,0.850982,0.873021,0.909940,0.927656,0.854117,0.058174,2
160,1.118787,0.029793,0.038180,0.000682,0.056560,entropy,36,sqrt,5,6,...,"{'estimator__ccp_alpha': 0.056560029047149914,...",0.785640,0.775871,0.844628,0.870580,0.910193,0.922128,0.851507,0.056128,3
198,1.040897,0.022126,0.039366,0.001058,0.000027,entropy,8,sqrt,19,17,...,{'estimator__ccp_alpha': 2.720351821722182e-05...,0.784390,0.783854,0.846354,0.865923,0.912247,0.912917,0.850947,0.052875,4
67,1.102484,0.032150,0.039963,0.001277,0.000178,entropy,55,log2,8,14,...,{'estimator__ccp_alpha': 0.0001783259272098575...,0.797158,0.778088,0.850923,0.862530,0.904375,0.912366,0.850906,0.049938,5
180,1.135826,0.030260,0.040101,0.000776,0.000151,entropy,47,log2,1,9,...,{'estimator__ccp_alpha': 0.0001511924737958250...,0.796466,0.764740,0.845097,0.871600,0.901079,0.923690,0.850445,0.055773,6
40,1.045540,0.019366,0.038608,0.001186,0.000139,entropy,49,sqrt,17,3,...,{'estimator__ccp_alpha': 0.0001389153089019249...,0.791771,0.781384,0.843274,0.879807,0.895372,0.910060,0.850278,0.049494,7
127,1.041363,0.020031,0.039313,0.001108,0.000111,log_loss,49,sqrt,19,16,...,{'estimator__ccp_alpha': 0.0001110846255422217...,0.784092,0.780089,0.838497,0.875670,0.904315,0.916592,0.849876,0.053863,8
44,1.119974,0.032273,0.038627,0.000519,0.022128,entropy,36,log2,3,19,...,"{'estimator__ccp_alpha': 0.022127954694182047,...",0.783966,0.761295,0.854167,0.860952,0.914003,0.922634,0.849503,0.060190,9
13,1.075083,0.025983,0.039165,0.001167,0.054526,log_loss,54,log2,13,10,...,"{'estimator__ccp_alpha': 0.05452561223245007, ...",0.788438,0.761019,0.843110,0.864554,0.910164,0.928951,0.849373,0.060301,10

In [23]:
best_params = results.iloc[0]["params"]

In [24]:
best_params.values()

dict_values([np.float64(6.368545516399493e-05), 'entropy', 3, 'log2', 3, 17, 200])

In [25]:
#values = list(best_params.values())
values = [np.float64(6.368545516399493e-05), 'entropy', 3, 'log2', 3, 17, 200] # For reproducibility

best_params = {
    "estimator__ccp_alpha": values[0],
    "estimator__criterion": values[1],
    "estimator__max_depth": values[2],
    "estimator__max_features": values[3],
    "estimator__min_samples_leaf": values[4],
    "estimator__min_samples_split": values[5],
    "estimator__n_estimators": values[6],
}

In [26]:
keys = []
for i in best_params.keys():
    keys.append(i.replace("estimator__", ""))

In [27]:
best_params = {k: i for (k,i) in zip(keys, best_params.values())}

In [28]:
best_params

{'ccp_alpha': np.float64(6.368545516399493e-05),
 'criterion': 'entropy',
 'max_depth': 3,
 'max_features': 'log2',
 'min_samples_leaf': 3,
 'min_samples_split': 17,
 'n_estimators': 200}

In [29]:
all_preds = []

aucs = []
for cv in cvs:

    X_train = X.iloc[cv[0]]
    X_test = X.iloc[cv[1]]

    y_train = y.iloc[cv[0]]
    y_test = y.iloc[cv[1]]

    model = MultiOutputClassifier(RandomForestClassifier(random_state=42, **best_params), n_jobs=-1)

    model.fit(X_train, y_train)
    y_probas = model.predict_proba(X_test)
    proba_inner = y_probas[0][:, 1]
    proba_outer = y_probas[1][:, 1]
    proba_ball = y_probas[2][:, 1]

    preds = np.array([proba_outer, proba_inner, proba_ball, y_test['outer'], y_test['inner'], y_test['ball']])
    all_preds.append(preds)

    auroc_outer = roc_auc_score(y_test["outer"], proba_outer)
    auroc_inner = roc_auc_score(y_test["inner"], proba_inner)
    auroc_ball = roc_auc_score(y_test["ball"], proba_ball)

    macro_auc = np.mean([auroc_outer, auroc_inner, auroc_ball])
    print(f"Macro AUC: {macro_auc:.4f} | Outer AUC: {auroc_outer:.4f} | Inner AUC: {auroc_inner:.4f} | Ball AUC: {auroc_ball:.4f}")
    aucs.append([macro_auc, auroc_outer, auroc_inner, auroc_ball])

Macro AUC: 0.7248 | Outer AUC: 0.4539 | Inner AUC: 0.9252 | Ball AUC: 0.7954
Macro AUC: 0.6952 | Outer AUC: 0.4234 | Inner AUC: 0.8358 | Ball AUC: 0.8263
Macro AUC: 0.8719 | Outer AUC: 0.9996 | Inner AUC: 0.6425 | Ball AUC: 0.9736
Macro AUC: 0.8630 | Outer AUC: 0.9996 | Inner AUC: 0.6237 | Ball AUC: 0.9658
Macro AUC: 0.8705 | Outer AUC: 0.9946 | Inner AUC: 0.7734 | Ball AUC: 0.8436
Macro AUC: 0.8509 | Outer AUC: 1.0000 | Inner AUC: 0.8085 | Ball AUC: 0.7443
Macro AUC: 0.7795 | Outer AUC: 0.5681 | Inner AUC: 0.9057 | Ball AUC: 0.8646
Macro AUC: 0.8120 | Outer AUC: 0.5923 | Inner AUC: 0.9078 | Ball AUC: 0.9358
Macro AUC: 0.7797 | Outer AUC: 0.5432 | Inner AUC: 0.9609 | Ball AUC: 0.8350
Macro AUC: 0.8334 | Outer AUC: 0.6036 | Inner AUC: 0.9905 | Ball AUC: 0.9060
Macro AUC: 0.6667 | Outer AUC: 0.3436 | Inner AUC: 0.9578 | Ball AUC: 0.6988
Macro AUC: 0.7815 | Outer AUC: 0.4322 | Inner AUC: 0.9983 | Ball AUC: 0.9139
Macro AUC: 0.6834 | Outer AUC: 0.4264 | Inner AUC: 0.9139 | Ball AUC: 0.7098
Macro AUC: 0.6770 | Outer AUC: 0.4625 | Inner AUC: 0.8846 | Ball AUC: 0.6838
Macro AUC: 0.9572 | Outer AUC: 1.0000 | Inner AUC: 0.9450 | Ball AUC: 0.9267
Macro AUC: 0.9783 | Outer AUC: 1.0000 | Inner AUC: 0.9947 | Ball AUC: 0.9400
Macro AUC: 0.8838 | Outer AUC: 1.0000 | Inner AUC: 0.8133 | Ball AUC: 0.8381
Macro AUC: 0.9718 | Outer AUC: 1.0000 | Inner AUC: 0.9442 | Ball AUC: 0.9712
Macro AUC: 0.9369 | Outer AUC: 1.0000 | Inner AUC: 0.9982 | Ball AUC: 0.8125
Macro AUC: 0.9354 | Outer AUC: 1.0000 | Inner AUC: 0.9825 | Ball AUC: 0.8238
Macro AUC: 0.7149 | Outer AUC: 0.4309 | Inner AUC: 0.9810 | Ball AUC: 0.7327
Macro AUC: 0.7500 | Outer AUC: 0.3275 | Inner AUC: 0.9480 | Ball AUC: 0.9746
Macro AUC: 0.8422 | Outer AUC: 1.0000 | Inner AUC: 0.6682 | Ball AUC: 0.8585
Macro AUC: 0.8768 | Outer AUC: 1.0000 | Inner AUC: 0.7245 | Ball AUC: 0.9059
Macro AUC: 0.8845 | Outer AUC: 0.9996 | Inner AUC: 0.8393 | Ball AUC: 0.8145
Macro AUC: 0.8971 | Outer AUC: 0.9997 | Inner AUC: 0.8647 | Ball AUC: 0.8270
Macro AUC: 0.9210 | Outer AUC: 0.9528 | Inner AUC: 0.9719 | Ball AUC: 0.8384
Macro AUC: 0.9621 | Outer AUC: 1.0000 | Inner AUC: 0.9925 | Ball AUC: 0.8938
Macro AUC: 0.9147 | Outer AUC: 0.9981 | Inner AUC: 0.9092 | Ball AUC: 0.8367
Macro AUC: 0.9464 | Outer AUC: 1.0000 | Inner AUC: 0.9592 | Ball AUC: 0.8802
Macro AUC: 0.9373 | Outer AUC: 1.0000 | Inner AUC: 0.9841 | Ball AUC: 0.8279
Macro AUC: 0.9623 | Outer AUC: 1.0000 | Inner AUC: 0.9573 | Ball AUC: 0.9296
Macro AUC: 0.8383 | Outer AUC: 0.9810 | Inner AUC: 0.7907 | Ball AUC: 0.7433
Macro AUC: 0.8301 | Outer AUC: 0.9921 | Inner AUC: 0.7939 | Ball AUC: 0.7043
Macro AUC: 0.9174 | Outer AUC: 0.9800 | Inner AUC: 0.9408 | Ball AUC: 0.8314
Macro AUC: 0.9113 | Outer AUC: 0.9875 | Inner AUC: 0.9204 | Ball AUC: 0.8260
Macro AUC: 0.8334 | Outer AUC: 0.7726 | Inner AUC: 0.8584 | Ball AUC: 0.8692
Macro AUC: 0.8265 | Outer AUC: 0.7979 | Inner AUC: 0.8050 | Ball AUC: 0.8766
Macro AUC: 0.9762 | Outer AUC: 1.0000 | Inner AUC: 0.9998 | Ball AUC: 0.9287
Macro AUC: 0.9721 | Outer AUC: 1.0000 | Inner AUC: 0.9700 | Ball AUC: 0.9465
Macro AUC: 0.8679 | Outer AUC: 0.9838 | Inner AUC: 0.7816 | Ball AUC: 0.8383
Macro AUC: 0.8636 | Outer AUC: 0.9886 | Inner AUC: 0.7640 | Ball AUC: 0.8382
Macro AUC: 0.8629 | Outer AUC: 0.7439 | Inner AUC: 0.9402 | Ball AUC: 0.9046
Macro AUC: 0.8621 | Outer AUC: 0.6869 | Inner AUC: 0.9596 | Ball AUC: 0.9398
Macro AUC: 0.7640 | Outer AUC: 0.5716 | Inner AUC: 0.9245 | Ball AUC: 0.7958
Macro AUC: 0.8586 | Outer AUC: 0.6451 | Inner AUC: 0.9972 | Ball AUC: 0.9334
Macro AUC: 0.9554 | Outer AUC: 0.9936 | Inner AUC: 0.9994 | Ball AUC: 0.8733
Macro AUC: 0.9777 | Outer AUC: 0.9880 | Inner AUC: 0.9810 | Ball AUC: 0.9641
Macro AUC: 0.9260 | Outer AUC: 1.0000 | Inner AUC: 0.9883 | Ball AUC: 0.7896
Macro AUC: 0.9165 | Outer AUC: 1.0000 | Inner AUC: 0.9298 | Ball AUC: 0.8198
Macro AUC: 0.9767 | Outer AUC: 0.9993 | Inner AUC: 0.9885 | Ball AUC: 0.9421
Macro AUC: 0.9595 | Outer AUC: 0.9993 | Inner AUC: 0.9254 | Ball AUC: 0.9538
Macro AUC: 0.5612 | Outer AUC: 0.3637 | Inner AUC: 0.7766 | Ball AUC: 0.5435
Macro AUC: 0.7432 | Outer AUC: 0.4595 | Inner AUC: 0.8552 | Ball AUC: 0.9149
Macro AUC: 0.7036 | Outer AUC: 0.6504 | Inner AUC: 0.7239 | Ball AUC: 0.7364
Macro AUC: 0.7810 | Outer AUC: 0.7013 | Inner AUC: 0.7800 | Ball AUC: 0.8617
Macro AUC: 0.8605 | Outer AUC: 0.9372 | Inner AUC: 0.7318 | Ball AUC: 0.9125
Macro AUC: 0.8767 | Outer AUC: 1.0000 | Inner AUC: 0.6921 | Ball AUC: 0.9380
Macro AUC: 0.8246 | Outer AUC: 0.7373 | Inner AUC: 0.9475 | Ball AUC: 0.7891
Macro AUC: 0.8757 | Outer AUC: 0.7788 | Inner AUC: 0.9327 | Ball AUC: 0.9155
Macro AUC: 0.8708 | Outer AUC: 0.7736 | Inner AUC: 0.8651 | Ball AUC: 0.9736
Macro AUC: 0.8366 | Outer AUC: 0.8118 | Inner AUC: 0.7328 | Ball AUC: 0.9653
Macro AUC: 0.8186 | Outer AUC: 0.7762 | Inner AUC: 0.7880 | Ball AUC: 0.8917
Macro AUC: 0.8157 | Outer AUC: 0.7642 | Inner AUC: 0.7283 | Ball AUC: 0.9547
Macro AUC: 0.7758 | Outer AUC: 0.7460 | Inner AUC: 0.8874 | Ball AUC: 0.6939
Macro AUC: 0.7318 | Outer AUC: 0.7668 | Inner AUC: 0.7449 | Ball AUC: 0.6837
Macro AUC: 0.8312 | Outer AUC: 0.7596 | Inner AUC: 0.9457 | Ball AUC: 0.7883
Macro AUC: 0.8801 | Outer AUC: 0.7276 | Inner AUC: 0.9623 | Ball AUC: 0.9505
Macro AUC: 0.6469 | Outer AUC: 0.3803 | Inner AUC: 0.9298 | Ball AUC: 0.6305
Macro AUC: 0.7650 | Outer AUC: 0.4454 | Inner AUC: 0.9922 | Ball AUC: 0.8575
Macro AUC: 0.8374 | Outer AUC: 0.9994 | Inner AUC: 0.7273 | Ball AUC: 0.7855
Macro AUC: 0.8832 | Outer AUC: 0.9994 | Inner AUC: 0.6774 | Ball AUC: 0.9729
Macro AUC: 0.7990 | Outer AUC: 0.6437 | Inner AUC: 0.9521 | Ball AUC: 0.8014
Macro AUC: 0.8079 | Outer AUC: 0.6306 | Inner AUC: 0.9538 | Ball AUC: 0.8394
Macro AUC: 0.8866 | Outer AUC: 0.7538 | Inner AUC: 0.9837 | Ball AUC: 0.9222
Macro AUC: 0.8686 | Outer AUC: 0.7513 | Inner AUC: 0.9217 | Ball AUC: 0.9329
Macro AUC: 0.8930 | Outer AUC: 0.9993 | Inner AUC: 0.7671 | Ball AUC: 0.9125
Macro AUC: 0.8891 | Outer AUC: 0.9994 | Inner AUC: 0.6903 | Ball AUC: 0.9775
Macro AUC: 0.8952 | Outer AUC: 0.7941 | Inner AUC: 0.9794 | Ball AUC: 0.9121
Macro AUC: 0.9036 | Outer AUC: 0.7708 | Inner AUC: 1.0000 | Ball AUC: 0.9400
Macro AUC: 0.8266 | Outer AUC: 0.5709 | Inner AUC: 0.9654 | Ball AUC: 0.9435
Macro AUC: 0.8360 | Outer AUC: 0.7187 | Inner AUC: 0.9977 | Ball AUC: 0.7916
Macro AUC: 0.8760 | Outer AUC: 0.9612 | Inner AUC: 0.6851 | Ball AUC: 0.9818
Macro AUC: 0.8891 | Outer AUC: 1.0000 | Inner AUC: 0.6988 | Ball AUC: 0.9683
Macro AUC: 0.9568 | Outer AUC: 0.9761 | Inner AUC: 0.9113 | Ball AUC: 0.9831
Macro AUC: 0.9605 | Outer AUC: 1.0000 | Inner AUC: 0.9103 | Ball AUC: 0.9712
Macro AUC: 0.7174 | Outer AUC: 0.4009 | Inner AUC: 0.9234 | Ball AUC: 0.8279
Macro AUC: 0.7467 | Outer AUC: 0.4954 | Inner AUC: 0.9862 | Ball AUC: 0.7585
Macro AUC: 0.7407 | Outer AUC: 0.3503 | Inner AUC: 0.9432 | Ball AUC: 0.9286
Macro AUC: 0.7081 | Outer AUC: 0.4108 | Inner AUC: 0.9588 | Ball AUC: 0.7547
Macro AUC: 0.9560 | Outer AUC: 1.0000 | Inner AUC: 0.9987 | Ball AUC: 0.8693
Macro AUC: 0.9913 | Outer AUC: 1.0000 | Inner AUC: 0.9872 | Ball AUC: 0.9867
Macro AUC: 0.8291 | Outer AUC: 0.7563 | Inner AUC: 0.9863 | Ball AUC: 0.7446
Macro AUC: 0.8027 | Outer AUC: 0.7088 | Inner AUC: 0.8936 | Ball AUC: 0.8058
Macro AUC: 0.9443 | Outer AUC: 0.9967 | Inner AUC: 0.9978 | Ball AUC: 0.8384
Macro AUC: 0.9178 | Outer AUC: 0.9976 | Inner AUC: 0.9655 | Ball AUC: 0.7903
Macro AUC: 0.9640 | Outer AUC: 0.9826 | Inner AUC: 0.9613 | Ball AUC: 0.9480
Macro AUC: 0.9714 | Outer AUC: 0.9893 | Inner AUC: 0.9493 | Ball AUC: 0.9757
Macro AUC: 0.7455 | Outer AUC: 0.9579 | Inner AUC: 0.7048 | Ball AUC: 0.5737
Macro AUC: 0.7664 | Outer AUC: 1.0000 | Inner AUC: 0.7108 | Ball AUC: 0.5883

In [30]:
macro_aucs = [i[0] for i in aucs]
np.mean(macro_aucs), np.std(macro_aucs)

(np.float64(0.8506758928571431), np.float64(0.08921265288714132))

In [32]:
# save all_preds np.array
#np.save("data/saved_logits/cwru/preds.npy", np.array(all_preds))

## SVM

In [33]:
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [34]:
estimator = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", MultiOutputClassifier(SVC(probability=True)))
])

random_search = RandomizedSearchCV(
    estimator=estimator,
    param_distributions={
        "clf__estimator__C": loguniform(1e-3, 1e3),
        "clf__estimator__gamma": ["scale", "auto"],
        "clf__estimator__kernel": ["rbf"],
    },
    n_iter=250,
    cv=val_cvs,
    scoring="roc_auc",
    verbose=2,
    n_jobs=-1,
    random_state=42
)

random_search.fit(X, y)

Fitting 6 folds for each of 250 candidates, totalling 1500 fits
[CV] END clf__estimator__C=3.907967156822881, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=3.907967156822881, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=3.907967156822881, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=3.907967156822881, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=3.907967156822881, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.4731474644815003, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.4731474644815003, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=3.907967156822881, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.4731474644815003, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.1767016940294795, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.1767016940294795, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.1767016940294795, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.1767016940294795, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.4731474644815003, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.4731474644815003, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.1767016940294795, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012606912518374074, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012606912518374074, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012606912518374074, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012606912518374074, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.4731474644815003, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012606912518374074, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=17.71884735480682, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=17.71884735480682, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=17.71884735480682, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=17.71884735480682, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.1767016940294795, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.3s
[CV] END clf__estimator__C=0.10051981180656774, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.002231010801867922, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=17.71884735480682, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.002231010801867922, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.10051981180656774, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.10051981180656774, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.10051981180656774, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.002231010801867922, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.10051981180656774, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.002231010801867922, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=17.71884735480682, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s[CV] END clf__estimator__C=0.10051981180656774, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s

[CV] END clf__estimator__C=0.002231010801867922, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012606912518374074, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.3s
[CV] END clf__estimator__C=0.002231010801867922, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=98.77700294007911, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=98.77700294007911, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0021800651586435186, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=4.676478725076045, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=98.77700294007911, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0021800651586435186, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=4.676478725076045, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0021800651586435186, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=4.676478725076045, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0021800651586435186, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.0021800651586435186, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=98.77700294007911, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=98.77700294007911, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s[CV] END clf__estimator__C=0.3905441275210791, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s

[CV] END clf__estimator__C=1.408146893930582, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=1.408146893930582, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0010108171343846386, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.0010108171343846386, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.3905441275210791, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0010108171343846386, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=1.408146893930582, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0021800651586435186, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012601639723276799, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.3905441275210791, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012601639723276799, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012601639723276799, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=4.676478725076045, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=98.77700294007911, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=695.8780103230359, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=695.8780103230359, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=695.8780103230359, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=4.676478725076045, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=4.676478725076045, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=1.408146893930582, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.3905441275210791, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.006870101665590026, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.5450293694558254, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=1.408146893930582, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=1.408146893930582, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.3905441275210791, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.006870101665590026, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=5.132347525675519, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.5450293694558254, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.006870101665590026, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.3905441275210791, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.5450293694558254, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=695.8780103230359, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=695.8780103230359, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=5.132347525675519, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=5.132347525675519, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0010108171343846386, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=695.8780103230359, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0010108171343846386, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=1.2173252504194043, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0010108171343846386, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012601639723276799, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.012601639723276799, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=1.2173252504194043, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=1.2173252504194043, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.5450293694558254, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.012601639723276799, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=5.132347525675519, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.6317967091932509, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.6317967091932509, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=4.418441521199722, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.5450293694558254, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s[CV] END clf__estimator__C=0.6317967091932509, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s

[CV] END clf__estimator__C=5.132347525675519, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=4.418441521199722, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=4.418441521199722, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=5.132347525675519, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.5450293694558254, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=493.52962094021007, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.006870101665590026, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=493.52962094021007, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.50465608220732, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=1.2173252504194043, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.50465608220732, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=493.52962094021007, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.50465608220732, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.006870101665590026, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=1.2173252504194043, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=2.3973382079286494, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.006870101665590026, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=1.2173252504194043, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=2.3973382079286494, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.6317967091932509, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=4.418441521199722, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=2.3973382079286494, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=4.418441521199722, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.6317967091932509, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=493.52962094021007, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.6317967091932509, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=4.418441521199722, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=493.52962094021007, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.50465608220732, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=493.52962094021007, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.50465608220732, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=2.3973382079286494, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.50465608220732, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.4374364439939078, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.06724850206557247, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=2.3973382079286494, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=4.570670843111899, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.06724850206557247, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=4.570670843111899, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.4374364439939078, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.4374364439939078, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.06724850206557247, clf__estimator__gamma=scale, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=4.570670843111899, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0242863893810436, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=2.3973382079286494, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.0242863893810436, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=0.0242863893810436, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.2s
[CV] END clf__estimator__C=9.443515687962675, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.22200545479787925, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=9.443515687962675, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.22200545479787925, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=9.443515687962675, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s
[CV] END clf__estimator__C=0.22200545479787925, clf__estimator__gamma=auto, clf__estimator__kernel=rbf; total time=   0.1s

RandomizedSearchCV(cv=[([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
                         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, ...],
                        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
                         94, 95, 96, 97, 98, 99, 140, 141, 142, 143, 144, 145,
                         146, 147, 148, 149, ...]),
                       ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 20, 21, 22, 23, 24, 25,
                         26, 27, 28, 29, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, ...],
                        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 140, 141, 142,
                         143...
                   estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                             ('clf',
                                              MultiOutputClassifier(estimator=SVC(probability=True)))]),
                   n_iter=250, n_jobs=-1,
                   param_distributions={'clf__estimator__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7fce186cfd90>,
                                        'clf__estimator__gamma': ['scale',
                                                                  'auto'],
                                        'clf__estimator__kernel': ['rbf']},
                   random_state=42, scoring='roc_auc', verbose=2)

In [35]:
results = pd.DataFrame(random_search.cv_results_).sort_values(by="rank_test_score")

In [36]:
results.iloc[0]

mean_fit_time                                                            0.105666
std_fit_time                                                             0.003547
mean_score_time                                                          0.015517
std_score_time                                                           0.000438
param_clf__estimator__C                                                  0.504656
param_clf__estimator__gamma                                                  auto
param_clf__estimator__kernel                                                  rbf
params                          {'clf__estimator__C': 0.50465608220732, 'clf__...
split0_test_score                                                        0.880283
split1_test_score                                                        0.793824
split2_test_score                                                        0.790104
split3_test_score                                                        0.774613
split4_test_score                                                        0.756235
split5_test_score                                                        0.755432
mean_test_score                                                          0.791749
std_test_score                                                           0.042267
rank_test_score                                                                 1
Name: 21, dtype: object

In [37]:
best_params = results.iloc[0]["params"]

In [38]:
best_params.values()

dict_values([np.float64(0.50465608220732), 'auto', 'rbf'])

In [39]:
keys = []
for i in best_params.keys():
    keys.append(i.replace("estimator__", ""))

In [40]:
best_params = {k: i for (k,i) in zip(keys, best_params.values())}

In [41]:
best_params = {k.replace("clf__", ""): v for k, v in best_params.items()}

In [42]:
best_params

{'C': np.float64(0.50465608220732), 'gamma': 'auto', 'kernel': 'rbf'}

In [43]:
# For reproducibility:
best_params = {'C': np.float64(0.50465608220732), 'gamma': 'auto', 'kernel': 'rbf'}

In [44]:
len(cvs[0][1])

360

In [47]:
aucs = []
for cv in cvs:

    X_train = X.iloc[cv[0]]
    X_test = X.iloc[cv[1]]

    y_train = y.iloc[cv[0]]
    y_test = y.iloc[cv[1]]

    model = Pipeline([
        ("scaler", StandardScaler()),
        ("clf", MultiOutputClassifier(SVC(random_state=42, **best_params, probability=True), n_jobs=-1))
    ])

    model.fit(X_train, y_train)
    y_probas = model.predict_proba(X_test)
    proba_outer = y_probas[1][:, 1]
    proba_inner = y_probas[0][:, 1]
    proba_ball = y_probas[2][:, 1]

    auroc_outer = roc_auc_score(y_test["outer"], proba_outer)
    auroc_inner = roc_auc_score(y_test["inner"], proba_inner)
    auroc_ball = roc_auc_score(y_test["ball"], proba_ball)

    macro_auc = np.mean([auroc_outer, auroc_inner, auroc_ball])
    print(f"Macro AUC: {macro_auc:.4f} | Outer AUC: {auroc_outer:.4f} | Inner AUC: {auroc_inner:.4f} | Ball AUC: {auroc_ball:.4f}")
    aucs.append([macro_auc, auroc_outer, auroc_inner, auroc_ball])

Macro AUC: 0.6887 | Outer AUC: 0.5709 | Inner AUC: 0.9717 | Ball AUC: 0.5234
Macro AUC: 0.6949 | Outer AUC: 0.5988 | Inner AUC: 0.9149 | Ball AUC: 0.5711
Macro AUC: 0.8691 | Outer AUC: 1.0000 | Inner AUC: 0.7004 | Ball AUC: 0.9070
Macro AUC: 0.8593 | Outer AUC: 1.0000 | Inner AUC: 0.7810 | Ball AUC: 0.7969
Macro AUC: 0.8560 | Outer AUC: 1.0000 | Inner AUC: 0.7697 | Ball AUC: 0.7983
Macro AUC: 0.8166 | Outer AUC: 1.0000 | Inner AUC: 0.7634 | Ball AUC: 0.6863
Macro AUC: 0.8140 | Outer AUC: 0.6957 | Inner AUC: 0.8228 | Ball AUC: 0.9234
Macro AUC: 0.8372 | Outer AUC: 0.6094 | Inner AUC: 0.9467 | Ball AUC: 0.9554
Macro AUC: 0.8366 | Outer AUC: 0.6975 | Inner AUC: 0.8999 | Ball AUC: 0.9125
Macro AUC: 0.8822 | Outer AUC: 0.7179 | Inner AUC: 0.9521 | Ball AUC: 0.9767
Macro AUC: 0.7138 | Outer AUC: 0.4666 | Inner AUC: 0.9438 | Ball AUC: 0.7309
Macro AUC: 0.7528 | Outer AUC: 0.5590 | Inner AUC: 0.9901 | Ball AUC: 0.7092
Macro AUC: 0.7012 | Outer AUC: 0.5221 | Inner AUC: 0.9538 | Ball AUC: 0.6278
Macro AUC: 0.7090 | Outer AUC: 0.6395 | Inner AUC: 0.9724 | Ball AUC: 0.5152
Macro AUC: 0.8925 | Outer AUC: 1.0000 | Inner AUC: 0.8123 | Ball AUC: 0.8651
Macro AUC: 0.8975 | Outer AUC: 1.0000 | Inner AUC: 0.8980 | Ball AUC: 0.7944
Macro AUC: 0.8310 | Outer AUC: 1.0000 | Inner AUC: 0.7970 | Ball AUC: 0.6959
Macro AUC: 0.8694 | Outer AUC: 1.0000 | Inner AUC: 0.9645 | Ball AUC: 0.6438
Macro AUC: 0.9029 | Outer AUC: 1.0000 | Inner AUC: 1.0000 | Ball AUC: 0.7088
Macro AUC: 0.8662 | Outer AUC: 1.0000 | Inner AUC: 0.9921 | Ball AUC: 0.6064
Macro AUC: 0.7239 | Outer AUC: 0.4833 | Inner AUC: 1.0000 | Ball AUC: 0.6886
Macro AUC: 0.6992 | Outer AUC: 0.4052 | Inner AUC: 0.9800 | Ball AUC: 0.7122
Macro AUC: 0.8718 | Outer AUC: 0.9955 | Inner AUC: 0.7465 | Ball AUC: 0.8732
Macro AUC: 0.8848 | Outer AUC: 1.0000 | Inner AUC: 0.8299 | Ball AUC: 0.8245
Macro AUC: 0.7904 | Outer AUC: 1.0000 | Inner AUC: 0.8076 | Ball AUC: 0.5635
Macro AUC: 0.8035 | Outer AUC: 1.0000 | Inner AUC: 0.8999 | Ball AUC: 0.5106
Macro AUC: 0.8812 | Outer AUC: 1.0000 | Inner AUC: 1.0000 | Ball AUC: 0.6437
Macro AUC: 0.8689 | Outer AUC: 1.0000 | Inner AUC: 0.9724 | Ball AUC: 0.6344
Macro AUC: 0.8250 | Outer AUC: 1.0000 | Inner AUC: 0.8818 | Ball AUC: 0.5931
Macro AUC: 0.8314 | Outer AUC: 1.0000 | Inner AUC: 0.9337 | Ball AUC: 0.5604
Macro AUC: 0.8628 | Outer AUC: 0.9935 | Inner AUC: 1.0000 | Ball AUC: 0.5948
Macro AUC: 0.8483 | Outer AUC: 1.0000 | Inner AUC: 0.9668 | Ball AUC: 0.5781
Macro AUC: 0.7963 | Outer AUC: 0.9821 | Inner AUC: 0.9129 | Ball AUC: 0.4939
Macro AUC: 0.7590 | Outer AUC: 0.9905 | Inner AUC: 0.8777 | Ball AUC: 0.4089
Macro AUC: 0.8321 | Outer AUC: 0.9219 | Inner AUC: 0.8498 | Ball AUC: 0.7246
Macro AUC: 0.7720 | Outer AUC: 0.9152 | Inner AUC: 0.9085 | Ball AUC: 0.4924
Macro AUC: 0.7197 | Outer AUC: 0.8248 | Inner AUC: 0.9352 | Ball AUC: 0.3989
Macro AUC: 0.7358 | Outer AUC: 0.8633 | Inner AUC: 0.9323 | Ball AUC: 0.4119
Macro AUC: 0.8913 | Outer AUC: 0.9950 | Inner AUC: 0.9883 | Ball AUC: 0.6905
Macro AUC: 0.8657 | Outer AUC: 1.0000 | Inner AUC: 0.8974 | Ball AUC: 0.6997
Macro AUC: 0.7861 | Outer AUC: 0.9442 | Inner AUC: 0.8029 | Ball AUC: 0.6112
Macro AUC: 0.7544 | Outer AUC: 0.9330 | Inner AUC: 0.8929 | Ball AUC: 0.4371
Macro AUC: 0.7875 | Outer AUC: 0.6915 | Inner AUC: 0.8846 | Ball AUC: 0.7863
Macro AUC: 0.7499 | Outer AUC: 0.6954 | Inner AUC: 0.9029 | Ball AUC: 0.6512
Macro AUC: 0.8026 | Outer AUC: 0.7804 | Inner AUC: 0.8384 | Ball AUC: 0.7889
Macro AUC: 0.8042 | Outer AUC: 0.7367 | Inner AUC: 0.9877 | Ball AUC: 0.6882
Macro AUC: 0.9248 | Outer AUC: 0.9933 | Inner AUC: 1.0000 | Ball AUC: 0.7812
Macro AUC: 0.9309 | Outer AUC: 1.0000 | Inner AUC: 0.9899 | Ball AUC: 0.8028
Macro AUC: 0.8546 | Outer AUC: 0.9934 | Inner AUC: 1.0000 | Ball AUC: 0.5704
Macro AUC: 0.8342 | Outer AUC: 1.0000 | Inner AUC: 0.9706 | Ball AUC: 0.5318
Macro AUC: 0.8709 | Outer AUC: 1.0000 | Inner AUC: 1.0000 | Ball AUC: 0.6126
Macro AUC: 0.8297 | Outer AUC: 0.9911 | Inner AUC: 0.9369 | Ball AUC: 0.5612
Macro AUC: 0.6658 | Outer AUC: 0.5954 | Inner AUC: 0.9180 | Ball AUC: 0.4841
Macro AUC: 0.7310 | Outer AUC: 0.6459 | Inner AUC: 0.9629 | Ball AUC: 0.5840
Macro AUC: 0.8311 | Outer AUC: 0.8125 | Inner AUC: 0.8314 | Ball AUC: 0.8494
Macro AUC: 0.8519 | Outer AUC: 0.7276 | Inner AUC: 0.9333 | Ball AUC: 0.8949
Macro AUC: 0.8355 | Outer AUC: 1.0000 | Inner AUC: 0.8262 | Ball AUC: 0.6802
Macro AUC: 0.7742 | Outer AUC: 1.0000 | Inner AUC: 0.7557 | Ball AUC: 0.5670
Macro AUC: 0.7714 | Outer AUC: 0.7986 | Inner AUC: 0.9696 | Ball AUC: 0.5459
Macro AUC: 0.8004 | Outer AUC: 0.8648 | Inner AUC: 0.9668 | Ball AUC: 0.5696
Macro AUC: 0.9045 | Outer AUC: 0.8481 | Inner AUC: 0.9254 | Ball AUC: 0.9400
Macro AUC: 0.8052 | Outer AUC: 0.8894 | Inner AUC: 0.8201 | Ball AUC: 0.7060
Macro AUC: 0.8188 | Outer AUC: 0.8579 | Inner AUC: 0.8950 | Ball AUC: 0.7033
Macro AUC: 0.7485 | Outer AUC: 0.8231 | Inner AUC: 0.8258 | Ball AUC: 0.5967
Macro AUC: 0.7893 | Outer AUC: 0.8602 | Inner AUC: 0.9368 | Ball AUC: 0.5709
Macro AUC: 0.7069 | Outer AUC: 0.8652 | Inner AUC: 0.8340 | Ball AUC: 0.4214
Macro AUC: 0.8210 | Outer AUC: 0.7496 | Inner AUC: 0.9502 | Ball AUC: 0.7630
Macro AUC: 0.8213 | Outer AUC: 0.7653 | Inner AUC: 0.9744 | Ball AUC: 0.7242
Macro AUC: 0.6696 | Outer AUC: 0.3650 | Inner AUC: 0.9542 | Ball AUC: 0.6896
Macro AUC: 0.7596 | Outer AUC: 0.5983 | Inner AUC: 0.9952 | Ball AUC: 0.6854
Macro AUC: 0.8232 | Outer AUC: 1.0000 | Inner AUC: 0.8150 | Ball AUC: 0.6546
Macro AUC: 0.8171 | Outer AUC: 0.9866 | Inner AUC: 0.7761 | Ball AUC: 0.6887
Macro AUC: 0.8268 | Outer AUC: 0.7201 | Inner AUC: 1.0000 | Ball AUC: 0.7603
Macro AUC: 0.7509 | Outer AUC: 0.6558 | Inner AUC: 1.0000 | Ball AUC: 0.5969
Macro AUC: 0.8175 | Outer AUC: 0.8102 | Inner AUC: 1.0000 | Ball AUC: 0.6422
Macro AUC: 0.7774 | Outer AUC: 0.7660 | Inner AUC: 0.9363 | Ball AUC: 0.6299
Macro AUC: 0.8007 | Outer AUC: 1.0000 | Inner AUC: 0.8219 | Ball AUC: 0.5801
Macro AUC: 0.7718 | Outer AUC: 0.9866 | Inner AUC: 0.7872 | Ball AUC: 0.5414
Macro AUC: 0.7914 | Outer AUC: 0.7734 | Inner AUC: 0.9736 | Ball AUC: 0.6271
Macro AUC: 0.7765 | Outer AUC: 0.7989 | Inner AUC: 0.9893 | Ball AUC: 0.5412
Macro AUC: 0.8511 | Outer AUC: 0.6550 | Inner AUC: 0.9147 | Ball AUC: 0.9836
Macro AUC: 0.8225 | Outer AUC: 0.7210 | Inner AUC: 0.9528 | Ball AUC: 0.7937
Macro AUC: 0.8509 | Outer AUC: 1.0000 | Inner AUC: 0.7520 | Ball AUC: 0.8008
Macro AUC: 0.8160 | Outer AUC: 1.0000 | Inner AUC: 0.7875 | Ball AUC: 0.6604
Macro AUC: 0.9848 | Outer AUC: 1.0000 | Inner AUC: 1.0000 | Ball AUC: 0.9544
Macro AUC: 0.9073 | Outer AUC: 1.0000 | Inner AUC: 0.9998 | Ball AUC: 0.7222
Macro AUC: 0.7033 | Outer AUC: 0.3437 | Inner AUC: 0.9694 | Ball AUC: 0.7967
Macro AUC: 0.7482 | Outer AUC: 0.5949 | Inner AUC: 0.9967 | Ball AUC: 0.6529
Macro AUC: 0.7822 | Outer AUC: 0.4829 | Inner AUC: 0.8859 | Ball AUC: 0.9779
Macro AUC: 0.6789 | Outer AUC: 0.4980 | Inner AUC: 0.9554 | Ball AUC: 0.5832
Macro AUC: 0.9153 | Outer AUC: 1.0000 | Inner AUC: 1.0000 | Ball AUC: 0.7459
Macro AUC: 0.9045 | Outer AUC: 0.9893 | Inner AUC: 0.9874 | Ball AUC: 0.7367
Macro AUC: 0.8037 | Outer AUC: 0.7731 | Inner AUC: 1.0000 | Ball AUC: 0.6381
Macro AUC: 0.7396 | Outer AUC: 0.7462 | Inner AUC: 0.9404 | Ball AUC: 0.5322
Macro AUC: 0.9504 | Outer AUC: 0.9911 | Inner AUC: 1.0000 | Ball AUC: 0.8602
Macro AUC: 0.9051 | Outer AUC: 1.0000 | Inner AUC: 0.9836 | Ball AUC: 0.7317
Macro AUC: 0.8663 | Outer AUC: 0.9442 | Inner AUC: 0.9411 | Ball AUC: 0.7136
Macro AUC: 0.8429 | Outer AUC: 0.9442 | Inner AUC: 0.9874 | Ball AUC: 0.5971
Macro AUC: 0.7299 | Outer AUC: 1.0000 | Inner AUC: 0.7685 | Ball AUC: 0.4213
Macro AUC: 0.7224 | Outer AUC: 1.0000 | Inner AUC: 0.7932 | Ball AUC: 0.3739

In [48]:
macro_aucs = [i[0] for i in aucs] 
np.mean(macro_aucs), np.std(macro_aucs)

(np.float64(0.8106799851190476), np.float64(0.06760377266990751))