# Feature Engineering

In this notebook, we calculate time and frequency domain features for the UORED-VAFCLS, CWRU and PU datasets. In order to simplify the process, we use an internally created library (FeatureExtraction). We maintain a similar segmentation strategy to deep learning experiments, with features calculated for 1s segments of each signal. The pipeline is executed with the combination of Hamilton + Hydra. 

All feature dataframes are stored in `data/features` folder.

In [1]:
import autorootcwd  # noqa
import pandas as pd
import numpy as np

from src.utils.add_signal_data import (
    add_signal_data_cwru,
    add_signal_data_ottawa,
    add_signal_data_paderborn
)

from hamilton import driver
from logging import INFO

import hydra
from hydra import compose, initialize
from omegaconf import OmegaConf
from hydra.core.hydra_config import HydraConfig

from src.data.feature_engineering import feature_extraction_pipeline
from src.utils.logger import setup_logger
from src.data.pydantic_models import BearingDataset
from src.data.preprocess import (
    preprocess_cwru,
    preprocess_ottawa,
    preprocess_paderborn
)

In [2]:
paderborn_metadata = pd.read_pickle(
    "data/metadata/paderborn/files_metadata.bz2"
)
cwru_metadata = pd.read_pickle(
    "data/metadata/cwru/files_metadata.bz2"
)
ottawa_metadata = pd.read_pickle(
    "data/metadata/ottawa/files_metadata.bz2"
)

In [3]:
paderborn_metadata

,waveform_id,bearing_id,bearing_manufacturer,repetition,load_torque,radial_force,rotational_speed,fault_label,severity,type_of_failure,...,bpfo,bpfi,bsf,ftf,multiclass_label,inner,outer,ball,cage,fs
0,N15_M07_F10_KA01_3,KA01,MTK,3,0.7,1000,1500,outer,1,artificial,...,3.0704,4.9296,2.036,0.3838,2,0,1,0,0,64000
1,N15_M01_F10_KA01_10,KA01,MTK,10,0.1,1000,1500,outer,1,artificial,...,3.0704,4.9296,2.036,0.3838,2,0,1,0,0,64000
2,N15_M07_F10_KA01_5,KA01,MTK,5,0.7,1000,1500,outer,1,artificial,...,3.0704,4.9296,2.036,0.3838,2,0,1,0,0,64000
3,N15_M07_F04_KA01_11,KA01,MTK,11,0.7,400,1500,outer,1,artificial,...,3.0704,4.9296,2.036,0.3838,2,0,1,0,0,64000
4,N15_M07_F10_KA01_15,KA01,MTK,15,0.7,1000,1500,outer,1,artificial,...,3.0704,4.9296,2.036,0.3838,2,0,1,0,0,64000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2635,N15_M07_F04_KA04_11,KA04,FAG,11,0.7,400,1500,outer,1,real,...,3.0548,4.9452,1.996,0.3819,2,0,1,0,0,64000
2636,N09_M07_F10_KA04_8,KA04,FAG,8,0.7,1000,900,outer,1,real,...,3.0548,4.9452,1.996,0.3819,2,0,1,0,0,64000
2637,N09_M07_F10_KA04_2,KA04,FAG,2,0.7,1000,900,outer,1,real,...,3.0548,4.9452,1.996,0.3819,2,0,1,0,0,64000
2638,N15_M01_F10_KA04_19,KA04,FAG,19,0.1,1000,1500,outer,1,real,...,3.0548,4.9452,1.996,0.3819,2,0,1,0,0,64000
2639,N15_M07_F10_KA04_14,KA04,FAG,14,0.7,1000,1500,outer,1,real,...,3.0548,4.9452,1.996,0.3819,2,0,1,0,0,64000

In [ ]:
# Initialize Hydra with the directory where your config is located'./configs/experiment'  # Folder containing the .yaml file
config_path = "../configs"
config_name = "feature_engineering"  # Name of your YAML file without extension


def get_configs(dataset="paderborn", segment=None, resample=False, overlap_pct=None):

    # Use Hydra to load the config
    with initialize(config_path=config_path, version_base="1.3"):
        cfg_hydra = compose(
            config_name=config_name,
            overrides=[f"+experiment/feature_eng=extract_features_{dataset}"],
            return_hydra_config=True,
        )
        HydraConfig().instance().set_config(cfg_hydra)  # Simular o @hydra.main
        cfg = compose(
            config_name=config_name,
            overrides=[f"+experiment/feature_eng=extract_features_{dataset}"],
        )
        cfg_dict = OmegaConf.to_container(cfg, resolve=True, throw_on_missing=True)

    datasets = hydra.utils.instantiate(cfg.datasets)
    feature_pipeline = hydra.utils.instantiate(cfg.feature_pipeline, _convert_="partial")
    # update_feature_store = hydra.utils.instantiate(cfg.update_feature_store)

    logger = setup_logger(
        name="Feature Engineering",
        log_file="logs/feature_engineering.log",
        format_str="%(asctime)s | %(levelname)s | %(message)s",
        level=INFO,
    )

    cfg_dict["datasets"] = datasets
    cfg_dict["feature_pipeline"] = feature_pipeline
    cfg_dict["logger"] = logger
    cfg_dict['segment'] = segment
    cfg_dict['resample'] = resample
    cfg_dict['overlap_pct'] = overlap_pct if overlap_pct is not None else 0.0

    return cfg_dict

In [5]:
dr = driver.Builder().with_config({}).with_modules(feature_extraction_pipeline).build()

In [6]:
dr;

In [7]:
cfg_dict = get_configs(dataset="cwru", segment=True, resample=True)
temp_out = dr.execute(["preprocess_data"], inputs=cfg_dict)

2026-07-05 08:28:19,525 | INFO | Reading metadata files
2026-07-05 08:28:19,525 INFO: Reading metadata files

Segmenting dataset CWRU. Original size: 411
Segmented dataset CWRU. New size: 3932

In [8]:
temp_out['preprocess_data'][0].metadata.head()

,waveform_id,fault_location,load,rpm,fault_type,fault_size,signal_location,fs,duration,bpfo,bpfi,bsf,ftf,inner,outer,ball,multiclass_label,signal,waveform_id_seg
0,IR_7_DE_DE_48_1HP,DE,1,1772,IR,7,DE,12000,10.129667,3.5848,5.4152,2.35675,0.39828,1,0,0,1,"[0.024905838072299957, 0.2673018276691437, -0....",IR_7_DE_DE_48_1HP_1
1,IR_7_DE_DE_48_1HP,DE,1,1772,IR,7,DE,12000,10.129667,3.5848,5.4152,2.35675,0.39828,1,0,0,1,"[0.29689961671829224, 0.37777552008628845, -0....",IR_7_DE_DE_48_1HP_2
2,IR_7_DE_DE_48_1HP,DE,1,1772,IR,7,DE,12000,10.129667,3.5848,5.4152,2.35675,0.39828,1,0,0,1,"[-0.03919564187526703, 0.09723416715860367, 0....",IR_7_DE_DE_48_1HP_3
3,IR_7_DE_DE_48_1HP,DE,1,1772,IR,7,DE,12000,10.129667,3.5848,5.4152,2.35675,0.39828,1,0,0,1,"[0.49927806854248047, -0.10768187791109085, -0...",IR_7_DE_DE_48_1HP_4
4,IR_7_DE_DE_48_1HP,DE,1,1772,IR,7,DE,12000,10.129667,3.5848,5.4152,2.35675,0.39828,1,0,0,1,"[0.050687432289123535, -0.20687751471996307, -...",IR_7_DE_DE_48_1HP_5

In [ ]:
all_features = []
datasets = ['paderborn', 'cwru', 'ottawa']
for dataset in datasets:

    cfg_dict = get_configs(dataset=dataset, segment=True, resample=False, overlap_pct=0.04 if dataset=='paderborn' else None)
    temp_out = dr.execute(["preprocess_data"], inputs=cfg_dict)
    df = temp_out['preprocess_data'][0].metadata

    if dataset == 'paderborn':
        paderborn_bearings =["K001", "K002", "K003", "K004", "K005", "K006","KA04", "KA15", "KA16", "KA22", "KA30","KI04", "KI14", "KI16", "KI18", "KI21", "KI17"]
        temp_out['preprocess_data'][0].metadata = df[df['bearing_id'].isin(paderborn_bearings)].reset_index(drop=True)
    
    if dataset == 'cwru':
        filtered_cwru = pd.read_pickle("data/splits/cwru/filtered_cwru.pkl")
        temp_out['preprocess_data'][0].metadata = df[df['waveform_id'].isin(filtered_cwru['waveform_id'])].reset_index(drop=True)


    features = dr.execute(["extract_features"], inputs=cfg_dict, overrides={"preprocess_data": temp_out['preprocess_data']})
    all_features.append(features['extract_features'][0].metadata)

In [ ]:
all_features[0].waveform_id.nunique(), all_features[1].waveform_id.nunique(), all_features[2].waveform_id.nunique()

In [10]:
all_features[0].shape, all_features[1].shape, all_features[2].shape # 4 segments per signal for paderborn, 10 segment per signal for cwru, 10 segments per signal for ottawa

((5440, 17), (1440, 27), (600, 27))

In [ ]:
all_features[0].to_parquet('data/features/paderborn_features_segmented.parquet')
all_features[1].to_parquet('data/features/cwru_features_segmented.parquet')
all_features[2].to_parquet('data/features/ottawa_features_segmented.parquet')

In [15]:
cwru_w_overlap = []
for dataset in ['cwru']:

    cfg_dict = get_configs(dataset=dataset, segment=True, resample=False, overlap_pct=0.53)
    temp_out = dr.execute(["preprocess_data"], inputs=cfg_dict)
    df = temp_out['preprocess_data'][0].metadata
    
    filtered_cwru = pd.read_pickle("data/splits/cwru/filtered_cwru.pkl")
    temp_out['preprocess_data'][0].metadata = df[df['waveform_id'].isin(filtered_cwru['waveform_id'])].reset_index(drop=True)

    features = dr.execute(["extract_features"], inputs=cfg_dict, overrides={"preprocess_data": temp_out['preprocess_data']})
    cwru_w_overlap.append(features['extract_features'][0].metadata)

2026-07-05 08:29:55,046 | INFO | Reading metadata files
2026-07-05 08:29:55,046 | INFO | Reading metadata files
2026-07-05 08:29:55,046 | INFO | Reading metadata files
2026-07-05 08:29:55,046 | INFO | Reading metadata files
2026-07-05 08:29:55,046 INFO: Reading metadata files
2026-07-05 08:29:55,393 | INFO | Extracting features for CWRU
2026-07-05 08:29:55,393 | INFO | Extracting features for CWRU
2026-07-05 08:29:55,393 | INFO | Extracting features for CWRU
2026-07-05 08:29:55,393 | INFO | Extracting features for CWRU
2026-07-05 08:29:55,393 INFO: Extracting features for CWRU

Segmenting dataset CWRU. Original size: 411
Segmented dataset CWRU. New size: 14002
Dataset shape before feature extraction: (2880, 19)
Dataset shape after feature extraction: (2880, 44)
Dropping columns: ['fault_location', 'load', 'rpm', 'fault_type', 'fault_size', 'signal_location', 'fs', 'duration', 'bpfo', 'bpfi', 'bsf', 'ftf', 'inner', 'outer', 'ball', 'multiclass_label', 'signal']

In [16]:
cwru_w_overlap[0].to_parquet('data/features/cwru_features_segmented20.parquet')